"""initial_schema

Revision ID: 61aa11b09d9f
Revises:
Create Date: 2026-04-21 15:40:46.633315

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "61aa11b09d9f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ------------------------------------------------------------------
    # Extensions — must exist before any table uses uuid_generate_v4() or
    # gin_trgm_ops. IF NOT EXISTS keeps this idempotent across environments
    # where the DBA may have pre-created them.
    # ------------------------------------------------------------------
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "communities",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("sip_domain", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "ready", "active", "suspended", name="community_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("current_version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sip_domain"),
    )
    op.create_index(
        "idx_communities_name_trgm",
        "communities",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index("idx_communities_status", "communities", ["status"], unique=False)
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("consumer_name", sa.String(length=64), nullable=False),
        sa.Column(
            "processed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "sync_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ack_status",
            postgresql.ENUM("pending", "acked", "failed", name="sync_ack_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("acked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("community_id", "version", name="sync_events_community_id_version_key"),
    )
    op.create_index(
        "idx_sync_events_pending",
        "sync_events",
        ["community_id", "version"],
        unique=False,
        postgresql_where=sa.text("ack_status = 'pending'"),
    )
    op.create_table(
        "sync_state",
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("last_full_sync_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "last_full_sync_version", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "last_delta_version", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("merkle_root", sa.String(length=128), nullable=True),
        sa.Column(
            "health_status",
            sa.String(length=16),
            server_default=sa.text("'healthy'"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("community_id"),
    )
    op.create_table(
        "units",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("unit_code", sa.String(length=64), nullable=False),
        sa.Column("building_no", sa.String(length=32), nullable=True),
        sa.Column("floor_no", sa.Integer(), nullable=True),
        sa.Column("room_no", sa.String(length=32), nullable=True),
        sa.Column(
            "ownership_status",
            postgresql.ENUM("owned", "sold", "pending_transfer", "rented", name="ownership_status"),
            server_default=sa.text("'owned'"),
            nullable=False,
        ),
        sa.Column(
            "occupancy_status",
            postgresql.ENUM("vacant", "occupied", "rented", name="occupancy_status"),
            server_default=sa.text("'vacant'"),
            nullable=False,
        ),
        sa.Column("sync_version", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("community_id", "unit_code", name="units_community_id_unit_code_key"),
    )
    op.create_index("idx_units_community", "units", ["community_id"], unique=False)
    op.create_index("idx_units_ownership", "units", ["ownership_status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("mobile", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM("owner", "tenant", "family", "admin", "staff", name="user_role"),
            nullable=False,
        ),
        sa.Column(
            "auth_status",
            postgresql.ENUM("pending", "verified", "revoked", name="auth_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("call_policy_group", sa.String(length=32), nullable=True),
        sa.Column(
            "friendship_enabled", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("community_id", "mobile", name="users_community_id_mobile_key"),
    )
    op.create_index("idx_users_community", "users", ["community_id"], unique=False)
    op.create_index("idx_users_mobile", "users", ["mobile"], unique=False)
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_table(
        "announcements",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            postgresql.ENUM("low", "normal", "high", "urgent", name="announcement_priority"),
            server_default=sa.text("'normal'"),
            nullable=False,
        ),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_announcements_community",
        "announcements",
        ["community_id", sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_actor",
        "audit_log",
        ["actor_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_audit_community_time",
        "audit_log",
        ["community_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "call_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("sip_call_id", sa.String(length=128), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("caller_user_id", sa.UUID(), nullable=True),
        sa.Column("callee_user_id", sa.UUID(), nullable=True),
        sa.Column("caller_sip_uri", sa.String(length=256), nullable=False),
        sa.Column("callee_sip_uri", sa.String(length=256), nullable=False),
        sa.Column("callee_type", sa.String(length=16), nullable=True),
        sa.Column(
            "call_status",
            postgresql.ENUM(
                "init", "ringing", "answered", "ended", "rejected", "failed", name="call_status"
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("answer_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("duration_sec", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("hangup_cause", sa.String(length=64), nullable=True),
        sa.Column(
            "billing_scope",
            postgresql.ENUM("user", "community", "free", name="billing_scope"),
            nullable=True,
        ),
        sa.Column(
            "token_cost",
            sa.Numeric(precision=18, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("reject_reason", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["callee_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["caller_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "community_id", "sip_call_id", name="call_logs_community_id_sip_call_id_key"
        ),
    )
    op.create_index(
        "idx_call_logs_callee",
        "call_logs",
        ["callee_user_id", sa.literal_column("start_time DESC")],
        unique=False,
    )
    op.create_index(
        "idx_call_logs_caller",
        "call_logs",
        ["caller_user_id", sa.literal_column("start_time DESC")],
        unique=False,
    )
    op.create_index(
        "idx_call_logs_community_start",
        "call_logs",
        ["community_id", sa.literal_column("start_time DESC")],
        unique=False,
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("consent_type", sa.String(length=64), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column(
            "granted_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_consent_user_type", "consent_records", ["user_id", "consent_type"], unique=False
    )
    op.create_table(
        "friend_mappings",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_a_id", sa.UUID(), nullable=False),
        sa.Column("user_b_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "active", "blocked", "removed", name="friend_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("initiated_by", sa.UUID(), nullable=False),
        sa.Column(
            "effective_from",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("effective_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("user_a_id < user_b_id", name="ck_sorted_users"),
        sa.CheckConstraint("user_a_id <> user_b_id", name="ck_distinct_users"),
        sa.ForeignKeyConstraint(
            ["initiated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_a_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_b_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_friend_active",
        "friend_mappings",
        ["user_a_id", "user_b_id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "payment_orders",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_ref", sa.String(length=128), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=8), server_default=sa.text("'TWD'"), nullable=False),
        sa.Column("token_credit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_payment_provider_ref", "payment_orders", ["provider", "provider_ref"], unique=False
    )
    op.create_index(
        "idx_payment_user",
        "payment_orders",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "sip_endpoints",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "transport", sa.String(length=16), server_default=sa.text("'tls'"), nullable=False
        ),
        sa.Column("context", sa.String(length=64), nullable=False),
        sa.Column(
            "codec_order",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("ARRAY['opus', 'PCMU', 'PCMA']"),
            nullable=False,
        ),
        sa.Column("webrtc_enabled", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "community_id", "username", name="sip_endpoints_community_id_username_key"
        ),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("idx_sip_endpoints_community", "sip_endpoints", ["community_id"], unique=False)
    op.create_index("idx_sip_endpoints_user", "sip_endpoints", ["user_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
        sa.Column(
            "priority",
            postgresql.ENUM("low", "normal", "high", "urgent", name="announcement_priority"),
            server_default=sa.text("'normal'"),
            nullable=False,
        ),
        sa.Column("due_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tasks_community_status", "tasks", ["community_id", "status"], unique=False)
    op.create_table(
        "token_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "scope", postgresql.ENUM("community", "user", name="token_scope"), nullable=False
        ),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("delta", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("external_ref", sa.String(length=128), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'community' AND user_id IS NULL) OR (scope = 'user' AND user_id IS NOT NULL)",
            name="ck_scope_owner",
        ),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "idx_ledger_community",
        "token_ledger",
        ["community_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_ledger_user",
        "token_ledger",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "user_unit_relations",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column(
            "relation_type",
            postgresql.ENUM("resident", "family", "tenant", name="relation_type"),
            nullable=False,
        ),
        sa.Column(
            "effective_from",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("effective_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from", name="ck_effective_range"
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_uur_unit",
        "user_unit_relations",
        ["unit_id"],
        unique=False,
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.create_index(
        "idx_uur_user",
        "user_unit_relations",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.create_table(
        "billing_records",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("call_id", sa.UUID(), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("token_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "billing_scope",
            postgresql.ENUM("user", "community", "free", name="billing_scope"),
            nullable=False,
        ),
        sa.Column("ledger_entry_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["call_id"], ["call_logs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["token_ledger.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id"),
    )
    op.create_index(
        "idx_billing_community",
        "billing_records",
        ["community_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Post-table DDL — functions, triggers, materialized view.
    # Mirrors docs/02-database-schema.sql lines 163-187, 360-405.
    # ------------------------------------------------------------------

    # token_ledger is append-only: block UPDATE and DELETE at the DB layer
    # so even a buggy service or a malicious actor cannot rewrite history.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION forbid_ledger_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'token_ledger is append-only';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER trg_forbid_ledger_update BEFORE UPDATE ON token_ledger "
        "FOR EACH ROW EXECUTE FUNCTION forbid_ledger_mutation()"
    )
    op.execute(
        "CREATE TRIGGER trg_forbid_ledger_delete BEFORE DELETE ON token_ledger "
        "FOR EACH ROW EXECUTE FUNCTION forbid_ledger_mutation()"
    )

    # Materialized view of current balances; refreshed on a cadence by the
    # billing worker. The unique index is required by REFRESH CONCURRENTLY.
    op.execute(
        """
        CREATE MATERIALIZED VIEW token_balances AS
        SELECT
            scope,
            community_id,
            user_id,
            COALESCE(SUM(delta), 0) AS balance,
            MAX(created_at) AS last_change_at
        FROM token_ledger
        GROUP BY scope, community_id, user_id
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_balances_key ON token_balances("
        "scope, community_id, "
        "COALESCE(user_id, '00000000-0000-0000-0000-000000000000'::UUID))"
    )

    # updated_at is DB-maintained (no ORM onupdate). Attach the trigger to
    # every table that has an updated_at column so the ORM never has to think
    # about clock drift or partial updates.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION tg_set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        DO $$
        DECLARE
            t TEXT;
        BEGIN
            FOR t IN SELECT table_name FROM information_schema.columns
                     WHERE column_name = 'updated_at' AND table_schema = 'public'
            LOOP
                EXECUTE format('CREATE TRIGGER trg_updated_at BEFORE UPDATE ON %I
                                FOR EACH ROW EXECUTE FUNCTION tg_set_updated_at()', t);
            END LOOP;
        END $$;
        """
    )

    # Any INSERT/UPDATE/DELETE on entities that edge nodes mirror must bump
    # the owning community's current_version so the next /sync/delta picks
    # up the change.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION tg_bump_community_version()
        RETURNS TRIGGER AS $$
        DECLARE
            cid UUID;
        BEGIN
            cid := COALESCE(NEW.community_id, OLD.community_id);
            UPDATE communities SET current_version = current_version + 1 WHERE id = cid;
            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("users", "units", "sip_endpoints", "friend_mappings"):
        op.execute(
            f"CREATE TRIGGER trg_{table}_version "
            f"AFTER INSERT OR UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION tg_bump_community_version()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ------------------------------------------------------------------
    # Pre-table teardown. The materialized view depends on token_ledger so
    # it MUST be dropped before the autogenerated drop_table runs.
    # Triggers attached to tables are dropped implicitly when those tables
    # are dropped below, so we only need to drop the standalone functions
    # and the MV here / after the tables.
    # ------------------------------------------------------------------
    op.execute("DROP MATERIALIZED VIEW IF EXISTS token_balances")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_billing_community", table_name="billing_records")
    op.drop_table("billing_records")
    op.drop_index(
        "idx_uur_user",
        table_name="user_unit_relations",
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.drop_index(
        "idx_uur_unit",
        table_name="user_unit_relations",
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.drop_table("user_unit_relations")
    op.drop_index(
        "idx_ledger_user",
        table_name="token_ledger",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index("idx_ledger_community", table_name="token_ledger")
    op.drop_table("token_ledger")
    op.drop_index("idx_tasks_community_status", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("idx_sip_endpoints_user", table_name="sip_endpoints")
    op.drop_index("idx_sip_endpoints_community", table_name="sip_endpoints")
    op.drop_table("sip_endpoints")
    op.drop_index("idx_payment_user", table_name="payment_orders")
    op.drop_index("idx_payment_provider_ref", table_name="payment_orders")
    op.drop_table("payment_orders")
    op.drop_index(
        "idx_friend_active",
        table_name="friend_mappings",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("friend_mappings")
    op.drop_index("idx_consent_user_type", table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index("idx_call_logs_community_start", table_name="call_logs")
    op.drop_index("idx_call_logs_caller", table_name="call_logs")
    op.drop_index("idx_call_logs_callee", table_name="call_logs")
    op.drop_table("call_logs")
    op.drop_index("idx_audit_community_time", table_name="audit_log")
    op.drop_index("idx_audit_actor", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("idx_announcements_community", table_name="announcements")
    op.drop_table("announcements")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index("idx_users_mobile", table_name="users")
    op.drop_index("idx_users_community", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_units_ownership", table_name="units")
    op.drop_index("idx_units_community", table_name="units")
    op.drop_table("units")
    op.drop_table("sync_state")
    op.drop_index(
        "idx_sync_events_pending",
        table_name="sync_events",
        postgresql_where=sa.text("ack_status = 'pending'"),
    )
    op.drop_table("sync_events")
    op.drop_table("processed_events")
    op.drop_index("idx_communities_status", table_name="communities")
    op.drop_index(
        "idx_communities_name_trgm",
        table_name="communities",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("communities")

    # Functions were referenced only by triggers attached to the tables we
    # just dropped, so they are orphaned now — safe to drop.
    op.execute("DROP FUNCTION IF EXISTS tg_bump_community_version()")
    op.execute("DROP FUNCTION IF EXISTS tg_set_updated_at()")
    op.execute("DROP FUNCTION IF EXISTS forbid_ledger_mutation()")

    # NOTE: extensions (uuid-ossp, pgcrypto, pg_trgm) are intentionally NOT
    # dropped — they may be used by other schemas or by future migrations,
    # and dropping them in a downgrade would be destructive beyond this
    # migration's scope.

    # Alembic autogenerate does not drop PostgreSQL ENUM types on downgrade.
    # Drop every enum declared in src/models/enums.py so the downgrade leaves
    # the schema truly empty and re-upgrading does not hit "type already exists".
    for enum_name in (
        "announcement_priority",
        "sync_ack_status",
        "billing_scope",
        "call_status",
        "token_scope",
        "friend_status",
        "relation_type",
        "auth_status",
        "user_role",
        "occupancy_status",
        "ownership_status",
        "community_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
